import Head from 'next/head'
import Header from '../components/Header'
import Movie from '../components/Movie'

export default function Home({data}) {
  console.log(data)
  return (
    <div className='bg-black pb-5'>
      <Head>
        <title>IMDb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Movie data={data} />
      
    </div>
  )
}

export async function getServerSideProps(context) {
  const res = await fetch('http://localhost:3000/').catch(err => console.log(err))
  const data = await res.json().catch(err => console.log(err))

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }
  }
}
